---
- name: Check if both nomad_server and nomad_client set
  fail: msg='nomad_server and nomad_client were both set. According to https://nomadproject.io/docs/agent/config.html, "Note that it is strongly recommended not to operate a node as both client and server".'
  when: nomad_server and nomad_client

- name: Ensure unzip exists
  apt: name=unzip state=present
  tags: nomad

- name: Create Nomad group
  group: name={{ nomad_group }} system=yes state=present
  when: nomad_server
  tags: nomad

- name: Create Nomad user
  user: >
    name={{ nomad_user }}
    shell=/bin/false
    createhome=no
    group={{ nomad_group }}
    system=yes
    state=present
  when: nomad_server
  tags: nomad

- name: Download Nomad
  get_url: >
    url={{ nomad_url }}
    dest={{ nomad_download_dir }}/nomad.zip
    sha256sum={{ nomad_sha256sum }}
  tags: nomad

- name: Unzip Nomad to installation directory
  command: unzip {{ nomad_download_dir }}/nomad.zip -d {{ nomad_install_dir }}
  args:
    creates: "{{ nomad_install_dir }}/nomad"
  tags: nomad

- name: Create Nomad configuration directory
  file: >
    path={{ nomad_config_dir }}
    owner=root
    group=root
    mode=0755
    state=directory
  tags: nomad

- name: Create Nomad data directory
  file: >
    path={{ nomad_data_dir }}
    owner={{ nomad_user }}
    group={{ nomad_group }}
    mode=0755
    state=directory
  tags: nomad

- include: upstart.yml
  when: ansible_distribution_release == 'trusty'

- include: systemd.yml
  when: ansible_distribution_release == 'xenial'

- name: Create Nomad configuration file
  template: >
    src=nomad.hcl.j2
    dest={{ nomad_config_dir }}/nomad.hcl
    owner=root
    group=root
    mode=0644
  notify: restart nomad
  tags: nomad

- name: Create Nomad server configuration file
  template: >
    src=server.hcl.j2
    dest={{ nomad_config_dir }}/server.hcl
    owner=root
    group=root
    mode=0644
  notify: restart nomad
  when: nomad_server
  tags: nomad

- name: Create Nomad client configuration file
  template: >
    src=client.hcl.j2
    dest={{ nomad_config_dir }}/client.hcl
    owner=root
    group=root
    mode=0644
  notify: restart nomad
  when: nomad_client
  tags: nomad

- name: Create Nomad Atlas configuration file
  template: >
    src=atlas.hcl.j2
    dest={{ nomad_config_dir }}/atlas.hcl
    owner=root
    group=root
    mode=0644
  notify: restart nomad
  when: nomad_atlas
  tags: nomad

- name: Create Nomad consul configuration file
  template: >
    src=consul.hcl.j2
    dest={{ nomad_config_dir }}/consul.hcl
    owner=root
    group=root
    mode=0644
  notify: restart nomad
  when: nomad_consul
  tags: nomad

- name: Ensure Nomad service is started and enabled on boot
  service: name={{ nomad_service_name }} state=started enabled=yes
  tags: nomad
  when: ansible_distribution_release == 'trusty'

- name: Ensure Nomad systemd service is enabled on boot
  command: systemctl enable nomad.service
  when: ansible_distribution_release == 'xenial'

- name: Ensure Nomad systemd service is started
  command: systemctl start nomad.service
  when: ansible_distribution_release == 'xenial'
